### ISSUE TITLE
Applications (Gedit, Libre office) are not listing the printers added in the ps-printer-app

### ISSUE THREAD

**Issue by kavinsivak** [OpenPrinting/ps-printer-app#6]
Hello

OS version: Ubuntu 21.04
Cups version: 2.3.3op2-3ubuntu3

I have added the HP LaserJet M227fdn printer using generic ppd in PS-Printer-app , but the added printer is not getting listed in the applications (GEdit, Libre Office) when I try to print.

**Comment by tillkamppeter** [comment]
Sorry, I overlooked this one after having helped you on the other one (perhaps I confused notifications).

This is due to print dialogs of user applications often use a too old CUPS API. This is solved at least in the GTK print dialog (GEdit, Thunderbird, evince, ...) in Ubuntu 21.10, to be released mid-October.

Otherwise, have also a look at my answers on issue #9.
